# Setup
title:        George Mason Institute of Electical and Electronics Engineers
tagline:      Advancing to the forefronts of technological innovation
baseurl:      ""
paginate:     1
locale:       "en"

# About/contact
author:
  name:       GMU IEEE
  url:        http://ieee-gmu.github.io 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
